### ISSUE TITLE
Makefile:25: recipe for target 'docker-machine' failed

### ISSUE THREAD

**Issue by swamper** [hypriot/image-builder-odroid-c2#12]
Tried a default install just following along with the guide. Ran it twice. Runs were separated by a reboot of the host. Got the same error both times.

`make docker-machine
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'boxcutter/ubuntu1404' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 2376 (guest) => 2376 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /home/swamper/Desktop/image-builder-odroid-c2 => /home/swamper/Desktop/image-builder-odroid-c2
==> default: Machine already provisioned. Run`vagrant provision`or use the`--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
docker-machine create -d generic \
  --generic-ssh-user vagrant \
  --generic-ssh-key "/home/swamper/Desktop/image-builder-odroid-c2/.vagrant/machines/default/virtualbox/private_key" \
  --generic-ip-address 127.0.0.1 \
  --generic-ssh-port 2222 \
  image-builder-odroid-c2
Host already exists: "image-builder-odroid-c2"
Makefile:25: recipe for target 'docker-machine' failed
make: *** [docker-machine] Error 1`

Anything else you might need just let me know. Host is Ubuntu 16.04 with docker, docker-compose, and docker-machine installed.

**Comment by StefanScherer** [comment]
@swamper Error seems that the docker-machine is already listed. Try 

```
vagrant up
docker-machine rm -f image-builder-odroid-c2
make docker-machine
```

After that you should be able to run the `eval ...` command to set the machine's env variables and then start `make sd-image`.

**Comment by swamper** [comment]
Wound up deleting the vm, the vagrant.d directory in home and re-cloned the repo. Still got the same error. The original setup would not even let me bring "`vagrant up`".

[hypriot-fail.txt](https://github.com/hypriot/image-builder-odroid-c2/files/313527/hypriot-fail.txt)

The entirety of the run I made on all fresh components for the build is in the txt file.
Only command given was `make docker-machine`.

**Comment by StefanScherer** [comment]
@swamper It still seems that the docker machine already exists. You do not have to delete .vagrant.d in home directory. And the created Vagrant VM is also not the problem.
Just check if the docker machine is listed

```
docker-machine ls
```

if it still shows image-builder-odroid-c2 then run

```
docker-machine rm -f image-builder-odroid-c2
```

Then `make docker-machine` should create the docker machine config again.

**Comment by swamper** [comment]
Ooops, sorry. That's what I get for doing that at 0330 after your first reply. It's running so this issue is closed.
