### ISSUE TITLE
Testing U-Boot from first SD card image

### ISSUE THREAD

**Issue by DieterReuter** [hypriot/image-builder-odroid-c2#4]
@umiddelb I've just created a first hopefully bootable SD card image and created a pre-release here https://github.com/hypriot/image-builder-odroid-c2/releases/tag/v0.0.3.

Please flash it to a SD card and test, if the C2 is able to load BL1 and BL2 bootloader stages and is able to start into U-Boot.

**Comment by umiddelb** [comment]
Hi @DieterReuter 

I cannot find the SD card image ... only the source code

**Comment by StefanScherer** [comment]
@umiddelb working on that, Travis deployment didn't work. Investigating...

**Comment by StefanScherer** [comment]
[Travis #11](https://travis-ci.org/hypriot/image-builder-odroid-c2/builds/109146694) in progress. Let's see if deployment works this time.

**Comment by StefanScherer** [comment]
Another rebuild in Travis 11. GitHub has swallowed the image. I had to remove the hidden image from release v0.0.3.

**Comment by StefanScherer** [comment]
Yet another error accessing `httpredir.debian.org` - we should consider switching to a specific server instead of this SPOF.

```
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/libx/libxshmfence/libxshmfence1_1.1-4_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
E: Failed to fetch http://httpredir.debian.org/debian/pool/main/g/graphite2/libgraphite2-3_1.2.4-3_amd64.deb  Error reading from server. Remote end closed connection [IP: 5.153.231.35 80]
```

**Comment by DieterReuter** [comment]
Just another restart of the job, hope it will work at least once for today!

**Comment by StefanScherer** [comment]
shellcheck passed. Keeping fingers crossed.

**Comment by DieterReuter** [comment]
Ping @umiddelb, download image v0.0.3 is available now!

**Comment by umiddelb** [comment]
image v0.0.3 needs an additional vfat partition in order to boot via cfgload/boot.ini
